### PR TITLE
FIXES config.js could not be found for unauthorized user

### PR DESCRIPTION
**Pull request by 0xMF**
Works with Chrome  42.0 on Win and on IE11

### CODE REVIEW

**Comment by matigo** [comment]
The `config.js` file needs to be created by the person running the site, so pointing to the sample would not be viable. When people update their repositories we don't want the defaults to overwrite their own values ... especially as config.js becomes more complex going forward.

Issue #23 will take care of this long term.

**Comment by 0xMF** [comment]
Good point, but now how can I get IE or Chrome to work with this repo on Windows and without config.js. In issue #22 I explained the problem I was having logging in with Chrome and IE.

**Comment by 0xMF** [comment]
@matigo @mttmccb sorry I didn't see your suggestion Matt before I commented here. Let me try what Matt suggests and I'll let you know. Even if I get this to work new people downloading the repo are bound to face the same problem.

**Comment by 0xMF** [comment]
@matigo @mttmccb All right I got this to work based on the [customization](https://github.com/matigo/nice_social#customisation) in the README. However as I want to build and test on Windows locally, I can only see filtered Global (fine for now) but again Chrome works fine but not IE11. As stated in issue #22  IE11 is not displaying anything. Now I wonder if config.js would simply work without me creating a client ID simply by using dummy values (I got Filtered Global with this PR #20).

**Comment by matigo** [comment]
You don't need real values in the `config.js` File, no. You will need a valid token if you wish to sign into ADN, though. Your repository is seen by the ADN servers as va separate app :)

**Pull request closed without merging**
